#!/usr/bin/env python3
"""
API Generator - Automatically generates HTTP API layer from C++ interface
"""

import re
import sys
from typing import List, Tuple

class APIFunction:
    def __init__(self, return_type: str, name: str, params: List[Tuple[str, str]]):
        self.return_type = return_type
        self.name = name
        self.params = params  # [(type, name), ...]
    
    def __repr__(self):
        return f"{self.return_type} {self.name}({', '.join(f'{t} {n}' for t, n in self.params)})"


def parse_interface(header_file: str) -> List[APIFunction]:
    """Parse the interface header and extract MIDDLEWARE_API marked functions"""
    
    with open(header_file, 'r') as f:
        content = f.read()
    
    # Remove comments
    content = re.sub(r'//.*', '', content)
    content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
    
    # Find all MIDDLEWARE_API marked functions
    # Support return types with :: (like std::string)
    pattern = r'MIDDLEWARE_API\s+([\w:]+(?:\s*\*)?)\s+(\w+)\s*\((.*?)\)\s*;'
    matches = re.findall(pattern, content, re.MULTILINE)
    
    functions = []
    for return_type, func_name, params_str in matches:
        return_type = return_type.strip()
        
        # Parse parameters
        params = []
        if params_str.strip():
            for param in params_str.split(','):
                param = param.strip()
                # Split type and name (handle pointers/refs)
                parts = param.rsplit(None, 1)
                if len(parts) == 2:
                    param_type, param_name = parts
                    params.append((param_type, param_name))
        
        functions.append(APIFunction(return_type, func_name, params))
    
    return functions


def generate_json_extractor(param_type: str, param_name: str) -> str:
    """Generate JSON extraction code based on parameter type"""
    
    type_map = {
        'int': f'int {param_name} = j["{param_name}"];',
        'float': f'float {param_name} = j["{param_name}"];',
        'double': f'double {param_name} = j["{param_name}"];',
        'bool': f'bool {param_name} = j["{param_name}"];',
        'std::string': f'std::string {param_name} = j["{param_name}"];',
        'string': f'std::string {param_name} = j["{param_name}"];',
    }
    
    return type_map.get(param_type, f'{param_type} {param_name} = j["{param_name}"];')


def generate_response_handler(return_type: str, result_var: str = "result") -> str:
    """Generate response JSON code based on return type"""
    
    if return_type == "void":
        return '''json response;
        response["status"] = "success";
        response["message"] = "Operation completed";'''
    elif return_type in ["int", "float", "double", "bool"]:
        return f'''json response;
        response["status"] = "success";
        response["result"] = {result_var};'''
    elif return_type in ["std::string", "string"]:
        return f'''json response;
        response["status"] = "success";
        response["message"] = {result_var};'''
    else:
        return f'''json response;
        response["status"] = "success";
        response["data"] = {result_var};'''


def generate_api_server(functions: List[APIFunction], output_file: str):
    """Generate the complete api_server.cpp file"""
    
    # Header
    code = '''// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by api_generator.py

#include "httplib.h"
#include "json.hpp"
#include "api_interface.h"
#include <iostream>

using json = nlohmann::json;

int main() {
    httplib::Server server;
    BusinessLogic logic;
    
'''
    
    # Generate routes for each function
    for func in functions:
        route_name = func.name
        
        code += f'''    // POST /{route_name}
    server.Post("/{route_name}", [&logic](const httplib::Request& req, httplib::Response& res) {{
        try {{
            auto j = json::parse(req.body);
            
'''
        
        # Extract parameters from JSON
        for param_type, param_name in func.params:
            code += f'            {generate_json_extractor(param_type, param_name)}\n'
        
        code += '\n'
        
        # Call business logic
        param_names = ', '.join(name for _, name in func.params)
        if func.return_type != "void":
            code += f'            {func.return_type} result = logic.{func.name}({param_names});\n'
        else:
            code += f'            logic.{func.name}({param_names});\n'
        
        code += '\n'
        
        # Generate response
        code += '            ' + generate_response_handler(func.return_type).replace('\n', '\n            ') + '\n'
        code += '            \n'
        code += '            res.set_content(response.dump(), "application/json");\n'
        code += '            \n'
        code += '        } catch (const std::exception& e) {\n'
        code += '            json error;\n'
        code += '            error["status"] = "error";\n'
        code += '            error["message"] = e.what();\n'
        code += '            res.status = 500;\n'
        code += '            res.set_content(error.dump(), "application/json");\n'
        code += '        }\n'
        code += '    });\n\n'
    
    # Footer
    code += '''    std::cout << "================================" << std::endl;
    std::cout << "API Server starting on port 8080..." << std::endl;
    std::cout << "Available endpoints:" << std::endl;
'''
    
    for func in functions:
        code += f'    std::cout << "  POST /{func.name}" << std::endl;\n'
    
    code += '''    std::cout << "================================" << std::endl;
    
    server.listen("0.0.0.0", 8080);
    return 0;
}
'''
    
    with open(output_file, 'w') as f:
        f.write(code)
    
    print(f"✅ Generated: {output_file}")
    print(f"📝 Found {len(functions)} API endpoints:")
    for func in functions:
        print(f"   - {func}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 api_generator.py <interface_header.h>")
        sys.exit(1)
    
    interface_file = sys.argv[1]
    output_file = "api_server.cpp"
    
    print(f"🔍 Parsing interface: {interface_file}")
    functions = parse_interface(interface_file)
    
    print(f"🔨 Generating API server...")
    generate_api_server(functions, output_file)
    
    print(f"\n✨ Done! Now run: make")
    print(f"Dependencies: httplib.h and json.hpp (included)")


if __name__ == "__main__":
    main()
