#!/usr/bin/env python3
"""
API Generator - Automatically generates HTTP API layer from C++ interface
"""

import re
import sys
from typing import List, Tuple

class APIFunction:
    def __init__(self, return_type: str, name: str, params: List[Tuple[str, str]]):
        self.return_type = return_type
        self.name = name
        self.params = params
    
    def __repr__(self):
        return f"{self.return_type} {self.name}({', '.join(f'{t} {n}' for t, n in self.params)})"


def parse_interface(header_file: str) -> List[APIFunction]:
    """Parse the interface header and extract MIDDLEWARE_API marked functions"""
    
    with open(header_file, 'r') as f:
        content = f.read()
    
    content = re.sub(r'//.*', '', content)
    content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
    
    pattern = r'MIDDLEWARE_API\s+([\w:]+(?:\s*\*)?)\s+(\w+)\s*\((.*?)\)\s*;'
    matches = re.findall(pattern, content, re.MULTILINE)
    
    functions = []
    for return_type, func_name, params_str in matches:
        return_type = return_type.strip()
        
        params = []
        if params_str.strip():
            for param in params_str.split(','):
                param = param.strip()
                parts = param.rsplit(None, 1)
                if len(parts) == 2:
                    param_type, param_name = parts
                    params.append((param_type, param_name))
        
        functions.append(APIFunction(return_type, func_name, params))
    
    return functions


def generate_param_extraction(param_type: str, param_name: str) -> str:
    """Generate parameter extraction using Mongoose's JSON parser"""
    
    if param_type in ['int', 'float', 'double']:
        return f'''double {param_name}_tmp = 0;
        mg_json_get_num(hm->body, "$.{param_name}", &{param_name}_tmp);
        {param_type} {param_name} = ({param_type}){param_name}_tmp;'''
    elif param_type == 'bool':
        return f'bool {param_name} = false; mg_json_get_bool(hm->body, "$.{param_name}", &{param_name});'
    elif param_type in ['std::string', 'string']:
        return f'''char* {param_name}_ptr = mg_json_get_str(hm->body, "$.{param_name}");
        std::string {param_name}({param_name}_ptr ? {param_name}_ptr : "");
        if ({param_name}_ptr) free({param_name}_ptr);'''
    else:
        return f'{param_type} {param_name}; // TODO: Custom extraction'


def generate_api_server(functions: List[APIFunction], output_file: str):
    """Generate the complete api_server.cpp file"""
    
    code = '''// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by api_generator.py

#include "mongoose.h"
#include "api_interface.h"
#include <iostream>
#include <string>
#include <cstring>
#include <cstdlib>

// Global business logic instance
static BusinessLogic* g_logic = nullptr;

// Helper to send JSON response
static void send_json(struct mg_connection *c, int status, const char* json) {
    mg_http_reply(c, status, "Content-Type: application/json\\r\\n", "%s", json);
}

'''
    
    # Generate handler for each function
    for func in functions:
        code += f'''// Handler for /{func.name}
static void handle_{func.name}(struct mg_connection *c, struct mg_http_message *hm) {{
    try {{
        // Extract parameters
'''
        
        for param_type, param_name in func.params:
            code += f'        {generate_param_extraction(param_type, param_name)}\n'
        
        code += '\n'
        
        # Call business logic
        param_names = ', '.join(name for _, name in func.params)
        if func.return_type != "void":
            code += f'        {func.return_type} result = g_logic->{func.name}({param_names});\n'
        else:
            code += f'        g_logic->{func.name}({param_names});\n'
        
        code += '\n'
        
        # Generate response
        if func.return_type == "void":
            code += '        send_json(c, 200, "{\\"status\\":\\"success\\",\\"message\\":\\"Operation completed\\"}");\n'
        elif func.return_type in ["int", "float", "double", "bool"]:
            code += '        char response[256];\n'
            code += f'        snprintf(response, sizeof(response), "{{\\"status\\":\\"success\\",\\"result\\":%g}}", (double)result);\n'
            code += '        send_json(c, 200, response);\n'
        elif func.return_type in ["std::string", "string"]:
            code += '        char response[1024];\n'
            code += '        snprintf(response, sizeof(response), "{\\"status\\":\\"success\\",\\"message\\":\\"%s\\"}", result.c_str());\n'
            code += '        send_json(c, 200, response);\n'
        
        code += '    } catch (const std::exception& e) {\n'
        code += '        char error[512];\n'
        code += '        snprintf(error, sizeof(error), "{\\"status\\":\\"error\\",\\"message\\":\\"%s\\"}", e.what());\n'
        code += '        send_json(c, 500, error);\n'
        code += '    }\n'
        code += '}\n\n'
    
    # Main event handler
    code += '''// Main HTTP event handler
static void http_handler(struct mg_connection *c, int ev, void *ev_data) {
    if (ev == MG_EV_HTTP_MSG) {
        struct mg_http_message *hm = (struct mg_http_message *) ev_data;
        
'''
    
    for func in functions:
        code += f'''        if (mg_match(hm->uri, mg_str("/{func.name}"), NULL)) {{
            handle_{func.name}(c, hm);
            return;
        }}
        
'''
    
    code += '''        // 404 Not Found
        send_json(c, 404, "{\\"status\\":\\"error\\",\\"message\\":\\"Endpoint not found\\"}");
    }
}

int main() {
    // Initialize business logic
    g_logic = new BusinessLogic();
    
    struct mg_mgr mgr;
    mg_mgr_init(&mgr);
    
    std::cout << "================================" << std::endl;
    std::cout << "API Server starting on port 8080..." << std::endl;
    std::cout << "Available endpoints:" << std::endl;
'''
    
    for func in functions:
        code += f'    std::cout << "  POST /{func.name}" << std::endl;\n'
    
    code += '''    std::cout << "================================" << std::endl;
    
    // Listen on port 8080
    mg_http_listen(&mgr, "0.0.0.0:8080", http_handler, NULL);
    
    // Event loop - stdout/stderr remain open!
    while (true) {
        mg_mgr_poll(&mgr, 1000);
    }
    
    mg_mgr_free(&mgr);
    delete g_logic;
    
    return 0;
}
'''
    
    with open(output_file, 'w') as f:
        f.write(code)
    
    print(f"Generated: {output_file}")
    print(f"Found {len(functions)} API endpoints:")
    for func in functions:
        print(f"   - {func}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 api_generator.py <interface_header.h>")
        sys.exit(1)
    
    interface_file = sys.argv[1]
    output_file = "api_server.cpp"
    
    print(f"Parsing interface: {interface_file}")
    functions = parse_interface(interface_file)
    
    print(f"Generating API server with Mongoose...")
    generate_api_server(functions, output_file)
    

if __name__ == "__main__":
    main()
