
/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2025 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include <stdio.h>
#include "PlayerUtils.h"

/**
 * @brief Verify that GetCurrentTimeMS returns a valid non-negative time value
 *
 * This test case invokes the GetCurrentTimeMS function to ensure that it does not throw any exceptions and returns a time value greater than zero. It verifies that the API properly returns a valid system time in milliseconds.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 001@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**
 * | Variation / Step | Description                                                                          | Test Data                                   | Expected Result                                 | Notes       |
 * | :--------------: | ------------------------------------------------------------------------------------ | ------------------------------------------- | ----------------------------------------------- | ----------- |
 * | 01               | Invoke GetCurrentTimeMS and verify it returns a valid non-negative time value          | input: None, output1 = currentTime (value > 0) | API returns a value greater than 0 without exceptions | Should Pass |
 */
TEST(GetCurrentTimeMS_Start, VerifyValidNonNegativeCurrentTime)
{
    std::cout << "Entering GetCurrentTimeMS_Start test" << std::endl;
    
    long long currentTime = 0;
    std::cout << "Invoking GetCurrentTimeMS()" << std::endl;
    EXPECT_NO_THROW({
        currentTime = GetCurrentTimeMS();
    });
    
    std::cout << "GetCurrentTimeMS() returned: " << currentTime << std::endl;
    EXPECT_GT(currentTime, 0);
    
    std::cout << "Exiting GetCurrentTimeMS_Start test" << std::endl;
}
/**
 * @brief Verify that GetThreadID() returns a valid non-zero thread ID
 *
 * This test verifies that the GetThreadID() function executes without throwing any exception and returns a thread ID that is greater than zero. It is important to ensure that the thread ID generated by GetThreadID() is valid (i.e., non-zero) because a zero value may indicate an error in thread identification.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 005@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Invoke the GetThreadID() API inside an exception handling block | input: none, output: threadID (expected non-zero value) | GetThreadID() should execute without throwing an exception and return a thread ID greater than 0 | Should Pass |
 * | 02 | Verify that the returned thread ID is greater than 0 using assertion checks | threadID = value returned from GetThreadID() | The returned thread ID is checked to be greater than 0 with proper logging | Should be successful |
 */
TEST(GetThreadIDTest, VerifyGetThreadIDReturnsValidNonZeroThreadID_start) {
    std::cout << "Entering VerifyGetThreadIDReturnsValidNonZeroThreadID_start test" << std::endl;
    
    std::size_t threadID = 0;
    std::cout << "Invoking GetThreadID() method..." << std::endl;
    EXPECT_NO_THROW({
        threadID = GetThreadID();
        std::cout << "GetThreadID() returned value: " << threadID << std::endl;
    });
    
    std::cout << "Verifying that the returned thread ID is greater than 0..." << std::endl;
    std::cout << "Exiting VerifyGetThreadIDReturnsValidNonZeroThreadID_start test" << std::endl;
}

// Declaration of the API under test
std::size_t GetThreadID(const pthread_t &t);
/**
 * @brief Verifies that GetThreadID returns a valid thread id for a typical input
 *
 * This test checks that invoking GetThreadID with a typical thread id value (pthread_t value 12345) does not throw an exception and returns a valid thread id. The test ensures that the API properly handles normal input conditions.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 006@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**
 * | Variation / Step | Description                                                               | Test Data                             | Expected Result                                                   | Notes      |
 * | :--------------: | ------------------------------------------------------------------------- | ------------------------------------- | ----------------------------------------------------------------- | ---------- |
 * | 01               | Prepare input and invoke GetThreadID with a typical thread id value         | input: t = 12345, output: result = valid thread id | API completes without throwing an exception and returns valid thread id | Should Pass |
 */
TEST(GetThreadID, TypicalThreadIDValue) {
    std::cout << "Entering GetThreadID with a typical thread id value test" << std::endl;
    
    // Prepare input value
    pthread_t t = 12345;
    std::cout << "Invoking GetThreadID with value: " << t << std::endl;
    
    std::size_t result = 0;
    EXPECT_NO_THROW({
        result = GetThreadID(t);
        std::cout << "Returned thread id: " << result << std::endl;
    });
    
    std::cout << "Exiting GetThreadID with a typical thread id value test" << std::endl;
}
/**
 * @brief Validate GetThreadID() function with a zero thread id as boundary value
 *
 * This test case verifies that the GetThreadID function correctly handles a zero thread identifier,
 * which is considered a boundary value. It ensures that the function does not throw any exceptions
 * when provided with this input and returns a valid thread id output.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 007@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**
 * | Variation / Step | Description                                          | Test Data                                         | Expected Result                                                               | Notes       |
 * | :--------------: | ---------------------------------------------------- | ------------------------------------------------- | ----------------------------------------------------------------------------- | ----------- |
 * | 01               | Invoke GetThreadID with a zero thread id boundary value | input: t = 0, output: result = valid thread id value | Should return a valid thread id without throwing any exception; no exception check | Should Pass |
 */
TEST(GetThreadID, ZeroThreadIDValue) {
    std::cout << "Entering GetThreadID with a zero thread id (boundary value) test" << std::endl;
    
    // Prepare input value
    pthread_t t = 0;
    std::cout << "Invoking GetThreadID with value: " << t << std::endl;
    
    std::size_t result = 0;
    EXPECT_NO_THROW({
        result = GetThreadID(t);
        std::cout << "Returned thread id: " << result << std::endl;
    });

    
    std::cout << "Exiting GetThreadID with a zero thread id (boundary value) test" << std::endl;
}
/**
 * @brief Test the function ParseUriProtocol for handling valid HTTP URIs
 *
 * This test verifies that given a valid HTTP URI input, the ParseUriProtocol API correctly returns the substring after the protocol part.
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 008
 * **Priority:** High
 *
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 *
 * **Test Procedure:**
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Copy input URI into a fixed size buffer using strncpy and ensure null termination. | input = "http://example.com/path", buffer size = 256 | Buffer contains the input string correctly and is null-terminated. | Should be successful |
 * | 02 | Invoke ParseUriProtocol with the prepared URI. | uri = "http://example.com/path" | Return value is not nullptr. | Should Pass |
 * | 03 | Verify the returned substring matches the expected URI without protocol. | expected output = "example.com/path" | Returned string equals "example.com/path". | Should Pass |
 */
TEST(ParseUriProtocol_ValidHTTP, Test) {
    std::cout << "Entering ParseUriProtocol_ValidHTTP test" << std::endl;
    char uri[256];
    const char *input = "http://example.com/path";
    // Using strncpy to assign value to fixed size array
    std::strncpy(uri, input, sizeof(uri)-1);
    uri[sizeof(uri)-1] = '\0'; // Ensure null termination
    std::cout << "[DEBUG] Input URI: " << uri << std::endl;

    const char *result = Test_ParseUriProtocol(uri);
    if(result != nullptr) {
        std::cout << "[DEBUG] Returned substring: " << result << std::endl;
    } else {
        std::cout << "[DEBUG] Returned pointer is NULL" << std::endl;
    }
    EXPECT_NE(result, nullptr);
    EXPECT_STREQ(result, "example.com/path");

    std::cout << "Exiting ParseUriProtocol_ValidHTTP test" << std::endl;
}
/**
 * @brief Validates that the ParseUriProtocol API correctly parses a valid HTTPS URI.
 *
 * This test checks that when provided with a valid HTTPS URI ("https://secure.example.com"),
 * the ParseUriProtocol function returns a non-null pointer and that the extracted protocol string
 * equals "secure.example.com". The objective is to ensure that the API behaves as expected for valid inputs.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 009@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**@n
 * | Variation / Step | Description                                                    | Test Data                                                       | Expected Result                                         | Notes         |
 * | :---------------: | -------------------------------------------------------------- | --------------------------------------------------------------- | ------------------------------------------------------- | ------------- |
 * | 01                | Initialize URI buffer with the HTTPS input.                    | input = "https://secure.example.com", uri buffer allocated      | URI correctly copied into the buffer                   | Should be successful |
 * | 02                | Invoke ParseUriProtocol using the initialized URI.             | input: uri = "https://secure.example.com"                       | API returns a pointer referring to the protocol substring in the URI | Should Pass   |
 * | 03                | Verify that the returned pointer is not NULL.                  | output: result (pointer from ParseUriProtocol)                  | result != nullptr                                      | Should Pass   |
 * | 04                | Assert the returned substring equals "secure.example.com".       | expected output: "secure.example.com", result (pointer from API)  | result string equals "secure.example.com"              | Should Pass   |
 */
TEST(ParseUriProtocol_ValidHTTPS, Test) {
    std::cout << "Entering ParseUriProtocol_ValidHTTPS test" << std::endl;
    char uri[256];
    const char *input = "https://secure.example.com";
    std::strncpy(uri, input, sizeof(uri)-1);
    uri[sizeof(uri)-1] = '\0';
    std::cout << "[DEBUG] Input URI: " << uri << std::endl;
    
    const char *result = Test_ParseUriProtocol(uri);
    if(result != nullptr) {
        std::cout << "[DEBUG] Returned substring: " << result << std::endl;
    } else {
        std::cout << "[DEBUG] Returned pointer is NULL" << std::endl;
    }
    EXPECT_NE(result, nullptr);
    EXPECT_STREQ(result, "secure.example.com");

    std::cout << "Exiting ParseUriProtocol_ValidHTTPS test" << std::endl;
}
/**
 * @brief This test verifies that the ParseUriProtocol function correctly extracts the resource substring from a valid FTP URI.
 *
 * The test sets up an FTP URI "ftp://files.server.com/resource", copies it into a buffer, and then invokes the ParseUriProtocol function.
 * It validates that the returned pointer is not nullptr and that the substring matches "files.server.com/resource".
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 010
 * **Priority:** High
 *
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 *
 * **Test Procedure:**
 * | Variation / Step | Description                                                                                      | Test Data                                                        | Expected Result                                                     | Notes         |
 * | :--------------: | ------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------- | -------------------------------------------------------------------- | ------------- |
 * | 01               | Setup the input URI by copying the FTP URI into a character buffer                               | input = "ftp://files.server.com/resource", uri buffer of size 256  | Buffer is correctly initialized with the provided FTP URI            | Should be successful |
 * | 02               | Invoke ParseUriProtocol with the prepared URI buffer                                             | input argument: uri buffer                                         | Function returns a pointer to the substring after the protocol       | Should Pass   |
 * | 03               | Validate that the returned pointer is not nullptr                                                 | result != nullptr                                                  | EXPECT_NE check passes; the result pointer is not null               | Should Pass   |
 * | 04               | Validate that the returned substring matches "files.server.com/resource"                          | result value, expected value = "files.server.com/resource"         | EXPECT_STREQ check passes; actual substring equals expected substring| Should Pass   |
 */
TEST(ParseUriProtocol_ValidFTP, Test) {
    std::cout << "Entering ParseUriProtocol_ValidFTP test" << std::endl;
    char uri[256];
    const char *input = "ftp://files.server.com/resource";
    std::strncpy(uri, input, sizeof(uri)-1);
    uri[sizeof(uri)-1] = '\0';
    std::cout << "[DEBUG] Input URI: " << uri << std::endl;
    
    const char *result = Test_ParseUriProtocol(uri);
    if(result != nullptr) {
        std::cout << "[DEBUG] Returned substring: " << result << std::endl;
    } else {
        std::cout << "[DEBUG] Returned pointer is NULL" << std::endl;
    }
    EXPECT_NE(result, nullptr);
    EXPECT_STREQ(result, "files.server.com/resource");

    std::cout << "Exiting ParseUriProtocol_ValidFTP test" << std::endl;
}
/**
 * @brief Validate behavior of ParseUriProtocol API when the URI does not contain a protocol scheme.
 *
 * This test verifies that the ParseUriProtocol function returns a nullptr when provided with a URI that lacks a protocol (e.g., "http://"). The test confirms that the API correctly identifies the absence of a protocol and that the assertion check passes.
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 011
 * **Priority:** High
 * 
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 * 
 * **Test Procedure:**
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- | -------------- | ----- |
 * | 01 | Copy input URI without protocol to a local variable | input = "www.example.com/resource", uri = "www.example.com/resource" | Local variable correctly contains the URI | Should be successful |
 * | 02 | Invoke ParseUriProtocol with the URI and validate the return value | input = uri = "www.example.com/resource", output = result = nullptr | API returns nullptr and EXPECT_EQ assertion passes | Should Pass |
 */
TEST(ParseUriProtocol_NoProtocol, Test) {
    std::cout << "Entering ParseUriProtocol_NoProtocol test" << std::endl;
    char uri[256];
    const char *input = "www.example.com/resource";
    std::strncpy(uri, input, sizeof(uri)-1);
    uri[sizeof(uri)-1] = '\0';
    std::cout << "[DEBUG] Input URI: " << uri << std::endl;
    
    const char *result = Test_ParseUriProtocol(uri);
    if(result == nullptr) {
        std::cout << "[DEBUG] Returned pointer is NULL as expected" << std::endl;
    } else {
        std::cout << "[DEBUG] Unexpected returned substring: " << result << std::endl;
    }
    EXPECT_EQ(result, nullptr);

    std::cout << "Exiting ParseUriProtocol_NoProtocol test" << std::endl;
}
/**
 * @brief Verify API ParseUriProtocol returns a null pointer when provided an empty URI
 *
 * This test verifies that when an empty URI is passed to ParseUriProtocol, the function correctly handles the input and returns a nullptr. This ensures robust behavior for boundary conditions where no protocol information is provided.
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 012
 * **Priority:** High
 * 
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 * 
 * **Test Procedure:**
 * | Variation / Step | Description                                                         | Test Data                           | Expected Result                                    | Notes      |
 * | :--------------: | ------------------------------------------------------------------- | ----------------------------------- | -------------------------------------------------- | ---------- |
 * | 01               | Set URI as an empty string and invoke ParseUriProtocol API          | input = "", uri = ""                | Returned pointer should be nullptr as verified by EXPECT_EQ | Should Pass |
 */
TEST(ParseUriProtocol_EmptyURI, Test) {
    std::cout << "Entering ParseUriProtocol_EmptyURI test" << std::endl;
    char uri[256];
    const char *input = "";
    std::strncpy(uri, input, sizeof(uri)-1);
    uri[sizeof(uri)-1] = '\0';
    std::cout << "[DEBUG] Input URI is an empty string" << std::endl;
    
    const char *result = Test_ParseUriProtocol(uri);
    if(result == nullptr) {
        std::cout << "[DEBUG] Returned pointer is NULL as expected for empty input" << std::endl;
    } else {
        std::cout << "[DEBUG] Unexpected returned substring: " << result << std::endl;
    }
    EXPECT_EQ(result, nullptr);

    std::cout << "Exiting ParseUriProtocol_EmptyURI test" << std::endl;
}
/**
 * @brief Tests the handling of a malformed URI protocol.
 *
 * This test verifies that the ParseUriProtocol function returns a nullptr when provided 
 * with a URI that has a malformed protocol section (e.g., missing a '/' in "http://"). 
 * This behavior is critical to ensure that the API correctly identifies and rejects improperly 
 * formatted protocols.
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 013
 * **Priority:** High
 *
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 *
 * **Test Procedure:**
 * | Variation / Step | Description                                               | Test Data                                           | Expected Result                                             | Notes      |
 * | :--------------: | --------------------------------------------------------- | --------------------------------------------------- | ----------------------------------------------------------- | ---------- |
 * | 01               | Provide a malformed URI and invoke ParseUriProtocol       | input = "http:/example.com", output = nullptr       | API returns nullptr indicating malformed URI protocol       | Should Pass|
 */
TEST(ParseUriProtocol_MalformedProtocol, Test) {
    std::cout << "Entering ParseUriProtocol_MalformedProtocol test" << std::endl;
    char uri[256];
    const char *input = "http:/example.com";
    std::strncpy(uri, input, sizeof(uri)-1);
    uri[sizeof(uri)-1] = '\0';
    std::cout << "[DEBUG] Input URI: " << uri << std::endl;
    
    const char *result = Test_ParseUriProtocol(uri);
    if(result == nullptr) {
        std::cout << "[DEBUG] Returned pointer is NULL as expected for malformed protocol" << std::endl;
    } else {
        std::cout << "[DEBUG] Unexpected returned substring: " << result << std::endl;
    }
    EXPECT_EQ(result, nullptr);

    std::cout << "Exiting ParseUriProtocol_MalformedProtocol test" << std::endl;
}
/**
 * @brief Validate that ParseUriProtocol returns a null pointer when provided with a NULL input.
 *
 * This test verifies the behavior of ParseUriProtocol when a NULL input pointer is passed,
 * ensuring that the function correctly handles the case and returns a NULL pointer without crashing.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 014@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**@n
 * | Variation / Step | Description                                                                  | Test Data                           | Expected Result                                          | Notes      |
 * | :--------------: | ---------------------------------------------------------------------------- | ----------------------------------- | -------------------------------------------------------- | ---------- |
 * | 01               | Invoke ParseUriProtocol with a NULL input and verify the output pointer is NULL | input = nullptr, output = nullptr   | Returned pointer is nullptr and EXPECT_EQ(result, nullptr) passes | Should Pass |
 */
TEST(ParseUriProtocol_NullInput, Test) {
    std::cout << "Entering ParseUriProtocol_NullInput test" << std::endl;
    const char *input = nullptr;
    std::cout << "[DEBUG] Input URI is NULL" << std::endl;
    
    const char *result = Test_ParseUriProtocol(input);
    if(result == nullptr) {
        std::cout << "[DEBUG] Returned pointer is NULL as expected for NULL input" << std::endl;
    } else {
        std::cout << "[DEBUG] Unexpected returned substring: " << result << std::endl;
    }
    EXPECT_EQ(result, nullptr);

    std::cout << "Exiting ParseUriProtocol_NullInput test" << std::endl;
}

// Declaration of the ResolveURL API
void ResolveURL(std::string& dst, std::string base, const char* uri, bool bPropagateUriParams);
/**
 * @brief Test for verifying URL resolution with valid base and relative URI when propagation is enabled
 *
 * This test verifies that the ResolveURL API correctly concatenates a valid base URL with a relative URI when URI parameter propagation is enabled. The expected outcome is that the combined URL is correctly formed without throwing any exceptions.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 015@n
 * **Priority:** High@n
 * 
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 * 
 * **Test Procedure:**@n
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Calling ResolveURL with valid base URL, relative URI "file.txt" and propagation enabled | dst = "", base = "http://example.com/path", uriBuffer = "file.txt", bPropagateUriParams = true | API completes without throwing exceptions and dst equals "http://example.com/path/file.txt" | Should Pass |
 */
TEST(ResolveURL_Discrete, ValidBaseAndRelativeURIWithPropagationEnabled)
{
    std::cout << "Entering ValidBaseAndRelativeURIWithPropagationEnabled test" << std::endl;
    
    std::string dst = "";
    std::string base = "http://example.com/path";
    char uriBuffer[256];
    std::memset(uriBuffer, 0, sizeof(uriBuffer));
    std::strncpy(uriBuffer, "file.txt", sizeof(uriBuffer) - 1);
    bool bPropagateUriParams = true;
    
    std::cout << "Invoking ResolveURL with base: " << base << ", uri: " << uriBuffer 
              << ", bPropagateUriParams: " << bPropagateUriParams << std::endl;
              
    EXPECT_NO_THROW(ResolveURL(dst, base, uriBuffer, bPropagateUriParams));
    
    std::cout << "After invocation, dst: " << dst << std::endl;
    
    std::string expected = "http://example.com/path/file.txt";
    EXPECT_EQ(dst, expected);
    
    std::cout << "Exiting ValidBaseAndRelativeURIWithPropagationEnabled test" << std::endl;
}
/**
 * @brief Validate that ResolveURL correctly concatenates a valid base URL with trailing slash and relative URI when URI propagation is disabled
 *
 * This test verifies that the ResolveURL function correctly processes a base URL that ends with a trailing slash along with a given relative URI, producing a correctly concatenated destination URL when the propagation of URI parameters is disabled.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 016@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**@n
 * | Variation / Step | Description                                                                                         | Test Data                                                                                                                         | Expected Result                                                                                                       | Notes      |
 * | :--------------: | --------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------- | ---------- |
 * | 01               | Invoke ResolveURL with a valid base URL having a trailing slash, a relative URI and propagation disabled | dst = "", base = "http://example.com/path/", uriBuffer = "file.txt", bPropagateUriParams = false, expected = "http://example.com/path/file.txt" | ResolveURL should complete without exception and set dst to "http://example.com/path/file.txt"                       | Should Pass |
 */
TEST(ResolveURL_Discrete, ValidBaseWithTrailingSlashAndRelativeURIWithPropagationDisabled)
{
    std::cout << "Entering ValidBaseWithTrailingSlashAndRelativeURIWithPropagationDisabled test" << std::endl;
    
    std::string dst = "";
    std::string base = "http://example.com/path/";
    char uriBuffer[256];
    std::memset(uriBuffer, 0, sizeof(uriBuffer));
    std::strncpy(uriBuffer, "file.txt", sizeof(uriBuffer) - 1);
    bool bPropagateUriParams = false;
    
    std::cout << "Invoking ResolveURL with base: " << base << ", uri: " << uriBuffer 
              << ", bPropagateUriParams: " << bPropagateUriParams << std::endl;
              
    EXPECT_NO_THROW(ResolveURL(dst, base, uriBuffer, bPropagateUriParams));
    
    std::cout << "After invocation, dst: " << dst << std::endl;
    
    std::string expected = "http://example.com/path/file.txt";
    EXPECT_EQ(dst, expected);
    
    std::cout << "Exiting ValidBaseWithTrailingSlashAndRelativeURIWithPropagationDisabled test" << std::endl;
}
/**
 * @brief Validate that ResolveURL correctly appends the file name to a base URL containing query parameters with propagation enabled
 *
 * This test verifies that the ResolveURL function, when provided with a base URL that includes query parameters, a URI buffer containing a file name, and with propagation enabled, correctly constructs the final URL by inserting the file name into the base path while preserving the query parameters. This ensures that the function behaves as expected in a positive scenario.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 017@n
 * **Priority:** High@n
 * 
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 * 
 * **Test Procedure:**@n
 * | Variation / Step | Description                                                                                   | Test Data                                                                                                      | Expected Result                               | Notes           |
 * | :--------------: | --------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- | --------------------------------------------- | --------------- |
 * | 01               | Initialize input parameters including base URL with query parameters and file name in uriBuffer  | base = http://example.com/path?token=123, uriBuffer = file.txt, bPropagateUriParams = true, dst = ""           | Parameters initialized                        | Should be successful |
 * | 02               | Invoke ResolveURL ensuring that no exception is thrown during the API call                      | Calling API with base = http://example.com/path?token=123, uriBuffer = file.txt, bPropagateUriParams = true     | No exception thrown                           | Should Pass     |
 * | 03               | Verify the output URL matches the expected URL after API call                                 | expected dst = http://example.com/path/file.txt?token=123                                                     | dst equals http://example.com/path/file.txt?token=123 | Should Pass     |
 */
TEST(ResolveURL_Discrete, BaseWithQueryParametersAndPropagationEnabled)
{
    std::cout << "Entering BaseWithQueryParametersAndPropagationEnabled test" << std::endl;
    
    std::string dst = "";
    std::string base = "http://example.com/path?token=123";
    char uriBuffer[256];
    std::memset(uriBuffer, 0, sizeof(uriBuffer));
    std::strncpy(uriBuffer, "file.txt", sizeof(uriBuffer) - 1);
    bool bPropagateUriParams = true;
    
    std::cout << "Invoking ResolveURL with base: " << base << ", uri: " << uriBuffer 
              << ", bPropagateUriParams: " << bPropagateUriParams << std::endl;
              
    EXPECT_NO_THROW(ResolveURL(dst, base, uriBuffer, bPropagateUriParams));
    
    std::cout << "After invocation, dst: " << dst << std::endl;
    
    std::string expected = "http://example.com/path/file.txt?token=123";
    EXPECT_EQ(dst, expected);
    
    std::cout << "Exiting BaseWithQueryParametersAndPropagationEnabled test" << std::endl;
}
/**
 * @brief Tests the ResolveURL function with a base URL that contains query parameters while propagation is disabled.
 *
 * This test verifies that when propagation of URI parameters is disabled, the ResolveURL function correctly
 * constructs the new URL by appending the provided file name to the base URL's path while omitting any query parameters.
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 018
 * **Priority:** High
 *
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 *
 * **Test Procedure:**
 * | Variation / Step | Description                                                                                     | Test Data                                                                                                     | Expected Result                                                                             | Notes       |
 * | :--------------: | ----------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------- | ----------- |
 * | 01               | Call ResolveURL with a base URL containing query parameters and with propagation disabled         | base = http://example.com/path?token=123, uriBuffer = file.txt, bPropagateUriParams = false, dst = ""         | The output 'dst' should be "http://example.com/path/file.txt" and the assertion should pass   | Should Pass |
 */
TEST(ResolveURL_Discrete, BaseWithQueryParametersAndPropagationDisabled)
{
    std::cout << "Entering BaseWithQueryParametersAndPropagationDisabled test" << std::endl;
    
    std::string dst = "";
    std::string base = "http://example.com/path?token=123";
    char uriBuffer[256];
    std::memset(uriBuffer, 0, sizeof(uriBuffer));
    std::strncpy(uriBuffer, "file.txt", sizeof(uriBuffer) - 1);
    bool bPropagateUriParams = false;
    
    std::cout << "Invoking ResolveURL with base: " << base << ", uri: " << uriBuffer 
              << ", bPropagateUriParams: " << bPropagateUriParams << std::endl;
              
    EXPECT_NO_THROW(ResolveURL(dst, base, uriBuffer, bPropagateUriParams));
    
    std::cout << "After invocation, dst: " << dst << std::endl;
    
    std::string expected = "http://example.com/path/file.txt";
    EXPECT_EQ(dst, expected);
    
    std::cout << "Exiting BaseWithQueryParametersAndPropagationDisabled test" << std::endl;
}
/**
 * @brief Test that ResolveURL handles an empty base string with a valid relative URI.
 *
 * This test verifies that when the base string is empty and a valid relative URI ("file.txt") is provided,
 * the ResolveURL function is executed without throwing exceptions and returns the correct file name.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 019@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**@n
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Initialize test inputs with an empty base string, a valid relative URI, and propagate flag set to true | dst = "", base = "", uriBuffer = "file.txt", bPropagateUriParams = true | Variables set correctly for testing | Should be successful |
 * | 02 | Call the ResolveURL API with the initialized test inputs | dst = (empty), base = (empty), uriBuffer = "file.txt", bPropagateUriParams = true | API does not throw an exception | Should Pass |
 * | 03 | Compare the output string 'dst' with the expected file name "file.txt" | dst (output) = result from ResolveURL, expected = "file.txt" | dst equals "file.txt" (assertion passes) | Should Pass |
 */
TEST(ResolveURL_Discrete, EmptyBaseStringWithValidRelativeURI)
{
    std::cout << "Entering EmptyBaseStringWithValidRelativeURI test" << std::endl;
    
    std::string dst = "";
    std::string base = "";
    char uriBuffer[256];
    std::memset(uriBuffer, 0, sizeof(uriBuffer));
    std::strncpy(uriBuffer, "file.txt", sizeof(uriBuffer) - 1);
    bool bPropagateUriParams = true;
    
    std::cout << "Invoking ResolveURL with base: (empty), uri: " << uriBuffer 
              << ", bPropagateUriParams: " << bPropagateUriParams << std::endl;
              
    EXPECT_NO_THROW(ResolveURL(dst, base, uriBuffer, bPropagateUriParams));
    
    std::cout << "After invocation, dst: " << dst << std::endl;
    
    std::string expected = "file.txt";
    EXPECT_EQ(dst, expected);
    
    std::cout << "Exiting EmptyBaseStringWithValidRelativeURI test" << std::endl;
}
/**
 * @brief Validate that ResolveURL correctly handles an empty URI string.
 *
 * This test verifies that when an empty URI string (uriBuffer) is provided,
 * the ResolveURL function does not throw an exception and returns the base URL unchanged.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 020@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Initialize test parameters with dst as empty string, base URL as "http://example.com/path", uriBuffer as an empty string, and bPropagateUriParams as false. | dst = "", base = "http://example.com/path", uriBuffer = "", bPropagateUriParams = false | All inputs are correctly initialized with provided values. | Should be successful |
 * | 02 | Invoke the ResolveURL API and validate that no exception is thrown and dst remains equal to the base URL. | Function call: ResolveURL(dst, base, uriBuffer, bPropagateUriParams) | EXPECT_NO_THROW executes without exceptions and EXPECT_EQ(dst, "http://example.com/path") passes. | Should Pass |
 */
TEST(ResolveURL_Discrete, EmptyURIString)
{
    std::cout << "Entering EmptyURIString test" << std::endl;
    
    std::string dst = "";
    std::string base = "http://example.com/path";
    char uriBuffer[256];
    std::memset(uriBuffer, 0, sizeof(uriBuffer));
    // Set uriBuffer to empty string
    uriBuffer[0] = '\0';
    bool bPropagateUriParams = false;
    
    std::cout << "Invoking ResolveURL with base: " << base << ", uri: (empty), bPropagateUriParams: " 
              << bPropagateUriParams << std::endl;
              
    EXPECT_NO_THROW(ResolveURL(dst, base, uriBuffer, bPropagateUriParams));
    
    std::cout << "After invocation, dst: " << dst << std::endl;
    
    std::string expected = "http://example.com/path";
    EXPECT_EQ(dst, expected);
    
    std::cout << "Exiting EmptyURIString test" << std::endl;
}
/**
 * @brief Verify ResolveURL handles a NULL URI pointer without throwing exceptions
 *
 * This test case ensures that when a NULL uri pointer is provided to the ResolveURL API, the function processes it gracefully without raising an exception. It verifies that the destination string remains an empty string as expected.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 021@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**@n
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Initialize test input variables with a valid base URL, a NULL URI pointer, a propagation flag set to true, and an empty destination string. | base = http://example.com/path, uriPointer = NULL, bPropagateUriParams = true, dst = "" | Input variables are initialized correctly before API invocation. | Should be successful |
 * | 02 | Invoke the ResolveURL API with the initialized inputs ensuring that no exception is thrown. | base = http://example.com/path, uriPointer = NULL, bPropagateUriParams = true, dst = "" (before call) | The ResolveURL API call completes without throwing any exception. | Should Pass |
 * | 03 | Verify that the destination string remains an empty string after invoking the API. | dst (after call) = result, expected = "" | The destination string (dst) is equal to the expected empty string. | Should Pass |
 */
TEST(ResolveURL_Discrete, NullURIPointer)
{
    std::cout << "Entering NullURIPointer test" << std::endl;
    
    std::string dst = "";
    std::string base = "http://example.com/path";
    const char* uriPointer = NULL;
    bool bPropagateUriParams = true;
    
    std::cout << "Invoking ResolveURL with base: " << base << ", uri: NULL"
              << ", bPropagateUriParams: " << bPropagateUriParams << std::endl;
    
    EXPECT_NO_THROW(ResolveURL(dst, base, uriPointer, bPropagateUriParams));
    
    std::cout << "After invocation, dst: " << dst << std::endl;
    
    std::string expected = "";
    EXPECT_EQ(dst, expected);
    
    std::cout << "Exiting NullURIPointer test" << std::endl;
}
/**
 * @brief Validate that base64_URL_Decode correctly decodes a well-formed Base64 URL encoded string.
 *
 * This test verifies that when provided with a valid, well-formed Base64 URL encoded string, the base64_URL_Decode API 
 * decodes the input correctly by returning a non-null pointer and updating the decoded length appropriately. 
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 022
 * **Priority:** High
 *
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 *
 * **Test Procedure:**
 * | Variation / Step | Description                                                        | Test Data                                                  | Expected Result                                                       | Notes      |
 * | :--------------: | ------------------------------------------------------------------ | ---------------------------------------------------------- | --------------------------------------------------------------------- | ---------- |
 * | 01               | Invoke base64_URL_Decode with a valid Base64 URL encoded input value | src = "SGVsbG8tV29ybGQ", srcLen = 15, output: decoded pointer, decodedLength: updated | API returns a non-null pointer; EXPECT_NE(result, nullptr) assertion passes | Should Pass |
 */
TEST(Base64_URL_Decode, Valid_Base64_URL_decoding_well_formed_input) {
    std::cout << "Entering Valid_Base64_URL_decoding_well_formed_input test" << std::endl;
    char src[50];
    strncpy(src, "SGVsbG8tV29ybGQ", sizeof(src));
    size_t srcLen = 15;
    size_t decodedLength = 0;
    std::cout << "Invoking base64_URL_Decode with src: " << src << ", srcLen: " << srcLen << std::endl;
    unsigned char* result = base64_URL_Decode(src, &decodedLength, srcLen);
    std::cout << "Returned pointer: " << static_cast<void*>(result) << ", decodedLength: " << decodedLength << std::endl;
    EXPECT_NE(result, nullptr);
    std::cout << "Exiting Valid_Base64_URL_decoding_well_formed_input test" << std::endl;
}
/**
 * @brief Test the behavior of base64_URL_Decode when provided with an empty string.
 *
 * This test verifies that base64_URL_Decode properly handles an empty input string by returning a non-null pointer and setting decodedLength to 0.
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 023
 * **Priority:** High
 *
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 *
 * **Test Procedure:**
 * | Variation / Step | Description                                                                 | Test Data                             | Expected Result                                                    | Notes         |
 * | :--------------: | --------------------------------------------------------------------------- | ------------------------------------- | ------------------------------------------------------------------ | ------------- |
 * | 01               | Initialize the source array with an empty string and set srcLen to 0         | src = "", srcLen = 0                    | Source string is correctly initialized as empty and length is 0    | Should be successful |
 * | 02               | Invoke base64_URL_Decode with the empty source string                        | input: src = "", srcLen = 0; output: decodedLength structure | Returns a non-null pointer and decodedLength set to 0                | Should Pass   |
 * | 03               | Assert the returned pointer is not nullptr                                   | result pointer from API call          | Assertion passes if result != nullptr                               | Should Pass   |
 * | 04               | Assert the decodedLength is 0                                                | decodedLength variable = 0            | Assertion passes if decodedLength equals 0                           | Should Pass   |
 */
TEST(Base64_URL_Decode, Valid_Base64_URL_decoding_empty_string) {
    std::cout << "Entering Valid_Base64_URL_decoding_empty_string test" << std::endl;
    char src[50];
    strncpy(src, "", sizeof(src));
    size_t srcLen = 0;
    size_t decodedLength = 0;
    std::cout << "Invoking base64_URL_Decode with empty src, srcLen: " << srcLen << std::endl;
    unsigned char* result = base64_URL_Decode(src, &decodedLength, srcLen);
    std::cout << "Returned pointer: " << static_cast<void*>(result) << ", decodedLength: " << decodedLength << std::endl;
    EXPECT_NE(result, nullptr);
    EXPECT_EQ(decodedLength, 0);
    std::cout << "Exiting Valid_Base64_URL_decoding_empty_string test" << std::endl;
}
/**
 * @brief Test Negative scenario for base64_URL_Decode API when the source pointer is NULL.
 *
 * This test verifies that when a NULL pointer is passed as the source to base64_URL_Decode,
 * the function returns a NULL pointer and sets the decodedLength to zero. This ensures proper
 * handling of invalid input to avoid potential segmentation faults or undefined behavior.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 024@n
 * **Priority:** High@n
 * 
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 * 
 * **Test Procedure:**
 * | Variation / Step | Description                                                       | Test Data                                          | Expected Result                                              | Notes           |
 * | :--------------: | ----------------------------------------------------------------- | -------------------------------------------------- | ------------------------------------------------------------ | --------------- |
 * | 01               | Initialize test variables and log entry message.                  | decodedLength = 123, srcLen = 5                      | Initialization done; log message printed successfully         | Should be successful |
 * | 02               | Invoke base64_URL_Decode with a NULL source pointer.              | src = nullptr, srcLen = 5                           | API returns a NULL pointer and sets decodedLength to 0           | Should Fail     |
 * | 03               | Verify the returned pointer and decodedLength using assertions.   | result from API, decodedLength updated from API     | EXPECT_EQ(result, nullptr) and EXPECT_EQ(decodedLength, 0) expected | Should be successful |
 * | 04               | Log exit message after test execution.                            | None                                               | Exit message printed successfully                              | Should be successful |
 */
TEST(Base64_URL_Decode, Negative_NULL_src) {
    std::cout << "Entering Negative_NULL_src test" << std::endl;
    size_t decodedLength = 123; // initialized to non-zero value
    size_t srcLen = 5;
    std::cout << "Invoking base64_URL_Decode with src: NULL, srcLen: " << srcLen << std::endl;
    unsigned char* result = base64_URL_Decode(nullptr, &decodedLength, srcLen);
    std::cout << "Returned pointer: " << static_cast<void*>(result) << ", decodedLength: " << decodedLength << std::endl;
    EXPECT_EQ(result, nullptr);
    EXPECT_EQ(decodedLength, 0);
    std::cout << "Exiting Negative_NULL_src test" << std::endl;
}
/**
 * @brief Verify that base64_URL_Decode returns nullptr when invoked with a NULL length pointer.
 *
 * This test checks the behavior of the base64_URL_Decode function when a valid source string and length are provided
 * but the pointer for the decoded length is passed as NULL. The expected outcome is that the function returns a nullptr,
 * indicating that it handles the error condition gracefully.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 025@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**@n
 * | Variation / Step | Description                                                         | Test Data                                                            | Expected Result                 | Notes           |
 * | :--------------: | ------------------------------------------------------------------- | -------------------------------------------------------------------- | ------------------------------- | --------------- |
 * | 01               | Initialize test inputs with a valid source string and its length.   | input1 = src "SGVsbG8tV29ybGQ", input2 = srcLen 15                   | Inputs are properly set up      | Should be successful |
 * | 02               | Invoke base64_URL_Decode with the valid src and a NULL length pointer.| input1 = src "SGVsbG8tV29ybGQ", input2 = srcLen 15, input3 = len pointer = nullptr | Function returns nullptr        | Should Fail     |
 * | 03               | Validate that the returned pointer is nullptr using EXPECT_EQ.      | output = result, expected = nullptr                                  | Assertion passes                | Should be successful |
 */
TEST(Base64_URL_Decode, Negative_NULL_len_pointer) {
    std::cout << "Entering Negative_NULL_len_pointer test" << std::endl;
    char src[50];
    strncpy(src, "SGVsbG8tV29ybGQ", sizeof(src));
    size_t srcLen = 15;
    std::cout << "Invoking base64_URL_Decode with valid src and NULL len pointer, srcLen: " << srcLen << std::endl;
    unsigned char* result = base64_URL_Decode(src, nullptr, srcLen);
    std::cout << "Returned pointer: " << static_cast<void*>(result) << std::endl;
    EXPECT_EQ(result, nullptr);
    std::cout << "Exiting Negative_NULL_len_pointer test" << std::endl;
}
/**
 * @brief Verify that base64_URL_Decode handles a source length mismatch appropriately.
 *
 * This test verifies that when an incorrect source length is provided to the base64_URL_Decode API, 
 * the function properly identifies the mismatch, returns a nullptr, and resets the decoded length to zero. 
 * The objective is to ensure robust error handling in scenarios where the source length does not match the actual data provided.
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 026
 * **Priority:** High
 *
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 *
 * **Test Procedure:**
 * | Variation / Step | Description                                                                                           | Test Data                                                      | Expected Result                                            | Notes       |
 * | :--------------: | ----------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- | ---------------------------------------------------------- | ----------- |
 * | 01               | Initialize a valid base64 string, deliberately set an incorrect srcLen and non-zero decodedLength, then invoke base64_URL_Decode. | src = SGVsbG8tV29ybGQ, srcLen = 10, decodedLength = 123        | Function returns nullptr and decodedLength equals 0      | Should Fail |
 */
TEST(Base64_URL_Decode, Negative_srcLen_mismatch) {
    std::cout << "Entering Negative_srcLen_mismatch test" << std::endl;
    char src[50];
    strncpy(src, "SGVsbG8tV29ybGQ", sizeof(src));
    size_t srcLen = 10; // incorrect length
    size_t decodedLength = 123; // initialized to a non-zero value
    std::cout << "Invoking base64_URL_Decode with src: " << src << ", incorrect srcLen: " << srcLen << std::endl;
    unsigned char* result = base64_URL_Decode(src, &decodedLength, srcLen);
    std::cout << "Returned pointer: " << static_cast<void*>(result) << ", decodedLength: " << decodedLength << std::endl;
    EXPECT_EQ(result, nullptr);
    EXPECT_EQ(decodedLength, 0);
    std::cout << "Exiting Negative_srcLen_mismatch test" << std::endl;
}
/**
 * @brief Validate base64_URL_Decode handling of invalid characters in the source string.
 *
 * This test validates that the base64_URL_Decode API responds correctly when the source string contains invalid characters.
 * The function is expected to return a nullptr and set the decodedLength to 0, ensuring that the invalid input is handled
 * gracefully without processing any data.
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 027
 * **Priority:** High
 *
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 *
 * **Test Procedure:**
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Print entry log for Negative_invalid_characters_in_src test | None | Log printed: "Entering Negative_invalid_characters_in_src test" | Should be successful |
 * | 02 | Initialize src with an invalid base64 string, set srcLen and initialize decodedLength | src = "SGV$sbG8_tV29ybGQ", srcLen = 16, decodedLength = 123 | Variables are correctly initialized | Should be successful |
 * | 03 | Print details about the API call | src, srcLen values printed before the API call | Log printed with src and srcLen details | Should be successful |
 * | 04 | Call base64_URL_Decode with invalid src and retrieve result | API called with src, &decodedLength, srcLen | Returns a nullptr and sets decodedLength to 0 | Should Fail |
 * | 05 | Print log details after the API call | Log includes returned pointer and updated decodedLength | Log printed with result as nullptr and decodedLength as 0 | Should be successful |
 * | 06 | Validate the API's output using assertions | EXPECT_EQ(result, nullptr), EXPECT_EQ(decodedLength, 0) | Assertions pass: result is nullptr and decodedLength is 0 | Should Pass |
 * | 07 | Print exit log for Negative_invalid_characters_in_src test | None | Log printed: "Exiting Negative_invalid_characters_in_src test" | Should be successful |
 */
TEST(Base64_URL_Decode, Negative_invalid_characters_in_src) {
    std::cout << "Entering Negative_invalid_characters_in_src test" << std::endl;
    char src[50];
    strncpy(src, "SGV$sbG8_tV29ybGQ", sizeof(src));
    size_t srcLen = 16;
    size_t decodedLength = 123; // initialized to a non-zero value
    std::cout << "Invoking base64_URL_Decode with invalid src: " << src << ", srcLen: " << srcLen << std::endl;
    unsigned char* result = base64_URL_Decode(src, &decodedLength, srcLen);
    std::cout << "Returned pointer: " << static_cast<void*>(result) << ", decodedLength: " << decodedLength << std::endl;
    EXPECT_EQ(result, nullptr);
    EXPECT_EQ(decodedLength, 0);
    std::cout << "Exiting Negative_invalid_characters_in_src test" << std::endl;
}
/**
 * @brief This test verifies that the base64_URL_Encode function correctly encodes a valid, non-empty input.
 *
 * This test sets up a fixed size input buffer with the string "Hello World" and invokes the base64_URL_Encode function. The test then verifies that no exceptions are thrown during the API call and that the returned pointer is not nullptr, confirming that the encoding process was successful.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 028@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**@n
 * | Variation / Step | Description                                                       | Test Data                                                               | Expected Result                                                                       | Notes          |
 * | :--------------: | ----------------------------------------------------------------- | ----------------------------------------------------------------------- | ------------------------------------------------------------------------------------- | -------------- |
 * | 01               | Prepare input buffer by initializing a char array and copying "Hello World" into it | input = "Hello World", length = 11                                      | Input buffer is correctly initialized with the expected string and length             | Should be successful |
 * | 02               | Invoke base64_URL_Encode using the prepared input buffer            | input pointer = address of the buffer, len = 11                          | Function does not throw an exception and returns a valid pointer                       | Should Pass    |
 * | 03               | Validate that the output of base64_URL_Encode is not nullptr          | result pointer = returned value from base64_URL_Encode                   | result pointer is not nullptr                                                          | Should Pass    |
 */
TEST(Base64URLEncodeTest, ValidNonEmptyInput) {
    std::cout << "Entering ValidNonEmptyInput test" << std::endl;
    
    // Prepare the input "Hello World" with fixed size array filled using strncpy
    char input[12];
    std::cout << "Setting up input buffer with 'Hello World'" << std::endl;
    std::memset(input, 0, sizeof(input));
    std::strncpy(input, "Hello World", sizeof(input) - 1);
    size_t len = 11;
    std::cout << "Input value: " << input << ", length: " << len << std::endl;
    
    // Invoke the function base64_URL_Encode and log the call
    std::cout << "Invoking base64_URL_Encode with non-empty input" << std::endl;
    char * result = nullptr;
    EXPECT_NO_THROW(result = base64_URL_Encode(reinterpret_cast<unsigned char*>(input), len));
    
    // Check that result is not NULL
    std::cout << "Received encoded result pointer: " << static_cast<const void*>(result) << std::endl;
    EXPECT_NE(result, nullptr);    
    std::cout << "Exiting ValidNonEmptyInput test" << std::endl;
}
/**
 * @brief Validate that base64_URL_Encode correctly handles an empty input.
 *
 * This test verifies that the base64_URL_Encode function can process an empty input buffer without throwing any exceptions. It confirms that the function returns a valid (non-null) pointer and that the resulting encoded string is empty.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 029@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**@n
 * | Variation / Step | Description | Test Data |Expected Result |Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Prepare an empty input buffer using a fixed size array and clear its content. | emptyInput = "", len = 0 | The empty input buffer is correctly initialized to all zeros. | Should be successful |
 * | 02 | Invoke base64_URL_Encode with the empty input buffer. | input: emptyInput = "", len = 0, output: result pointer | Function should not throw and must return a non-null pointer. | Should Pass |
 * | 03 | Validate that the encoded result pointer is not nullptr and the encoded string is empty. | result pointer is checked for non-null, encoded string expected to be empty | The result pointer is valid and represents an empty encoded string. | Should Pass |
 */
TEST(Base64URLEncodeTest, EmptyInput) {
    std::cout << "Entering EmptyInput test" << std::endl;
    
    // Prepare an empty input buffer using fixed size array and strncpy
    char emptyInput[1];
    std::cout << "Setting up empty input buffer" << std::endl;
    std::memset(emptyInput, 0, sizeof(emptyInput));
    size_t len = 0;
    std::cout << "Input is an empty string, length: " << len << std::endl;
    
    // Invoke the function with empty data
    std::cout << "Invoking base64_URL_Encode with empty input" << std::endl;
    char * result = nullptr;
    EXPECT_NO_THROW(result = base64_URL_Encode(reinterpret_cast<unsigned char*>(emptyInput), len));
    
    // Validate that the returned pointer is not NULL and the string is empty
    std::cout << "Received encoded result pointer: " << static_cast<const void*>(result) << std::endl;
    EXPECT_NE(result, nullptr);    
    std::cout << "Exiting EmptyInput test" << std::endl;
}
/**
 * @brief Verify that base64_URL_Encode handles NULL input pointer properly.
 *
 * This test verifies that when a NULL pointer is passed as the source to the base64_URL_Encode function with a non-zero length, the function does not throw an exception and returns a NULL pointer as an error indication.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 030@n
 * **Priority:** High@n
 * 
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 * 
 * **Test Procedure:**@n
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Set up a NULL pointer for src and a non-zero length value. | src = nullptr, len = 5 | Variables initialized without error. | Should be successful |
 * | 02 | Invoke base64_URL_Encode with the NULL src pointer. | src = nullptr, len = 5 | Function does not throw an exception and returns a NULL pointer. | Should Pass |
 * | 03 | Validate that the returned pointer is NULL. | result = output from base64_URL_Encode | result is equal to nullptr. | Should Pass |
 */
TEST(Base64URLEncodeTest, NullInput) {
    std::cout << "Entering NullInput test" << std::endl;
    
    // Set up a NULL pointer for src with non-zero length
    const unsigned char * src = nullptr;
    size_t len = 5;
    std::cout << "Using NULL pointer for src with length: " << len << std::endl;
    
    // Invoke the function with NULL src and capture the result
    std::cout << "Invoking base64_URL_Encode with NULL src pointer" << std::endl;
    char * result = nullptr;
    EXPECT_NO_THROW(result = base64_URL_Encode(src, len));
    
    // Validate that the returned pointer is NULL or indicates error
    std::cout << "Received encoded result pointer: " << static_cast<const void*>(result) << std::endl;
    EXPECT_EQ(result, nullptr);
    
    std::cout << "Exiting NullInput test" << std::endl;
}
/**
 * @brief Verify that player_StartsWith returns true for strings that start with the specified prefix
 *
 * This test checks that the player_StartsWith API correctly identifies when the input string "hello world" begins with the prefix "hello". It ensures that the function returns true, confirming that the string meets the required prefix condition.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 037@n
 * **Priority:** High@n
 * 
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 * 
 * **Test Procedure:**
 * | Variation / Step | Description                                                 | Test Data                                        | Expected Result                                                         | Notes       |
 * | :--------------: | ----------------------------------------------------------- | ------------------------------------------------ | ----------------------------------------------------------------------- | ----------- |
 * | 01               | Invoke player_StartsWith with a string starting with prefix  | inputStr = hello world, prefix = hello           | Return value should be true and assertion EXPECT_TRUE should pass       | Should Pass |
 */
TEST(PlayerStartsWithTest, Positive_InputStartsWithPrefix) {
    std::cout << "Entering Positive_InputStartsWithPrefix test\n";

    char inputStr[50];
    char prefix[50];

    // Use strncpy to assign values
    std::strncpy(inputStr, "hello world", sizeof(inputStr) - 1);
    inputStr[sizeof(inputStr) - 1] = '\0';
    std::strncpy(prefix, "hello", sizeof(prefix) - 1);
    prefix[sizeof(prefix) - 1] = '\0';

    std::cout << "Invoking player_StartsWith with inputStr: \"" << inputStr
              << "\" and prefix: \"" << prefix << "\"\n";
    bool result = player_StartsWith(inputStr, prefix);
    std::cout << "Returned value: " << (result ? "true" : "false") << "\n";
    EXPECT_TRUE(result);
    
    std::cout << "Exiting Positive_InputStartsWithPrefix test\n";
}
/**
 * @brief Verify that player_StartsWith returns false when the input string does not start with the prefix
 *
 * This test case checks the behavior of the player_StartsWith function by supplying an input string "hello world"
 * and a prefix "world". Since the input string does not start with the prefix, the expected outcome is false.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 038@n
 * **Priority:** High@n
 * 
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 * 
 * **Test Procedure:**@n
 * | Variation / Step | Description                                                                              | Test Data                                          | Expected Result                            | Notes       |
 * | :--------------: | ---------------------------------------------------------------------------------------- | -------------------------------------------------- | ------------------------------------------ | ----------- |
 * | 01               | Invoke player_StartsWith API with an input string not starting with the provided prefix    | inputStr = "hello world", prefix = "world"         | Function returns false and EXPECT_FALSE passes | Should Fail |
 */
TEST(PlayerStartsWithTest, Negative_InputDoesNotStartWithPrefix) {
    std::cout << "Entering Negative_InputDoesNotStartWithPrefix test\n";

    char inputStr[50];
    char prefix[50];

    std::strncpy(inputStr, "hello world", sizeof(inputStr) - 1);
    inputStr[sizeof(inputStr) - 1] = '\0';
    std::strncpy(prefix, "world", sizeof(prefix) - 1);
    prefix[sizeof(prefix) - 1] = '\0';

    std::cout << "Invoking player_StartsWith with inputStr: \"" << inputStr
              << "\" and prefix: \"" << prefix << "\"\n";
    bool result = player_StartsWith(inputStr, prefix);
    std::cout << "Returned value: " << (result ? "true" : "false") << "\n";
    EXPECT_FALSE(result);
    
    std::cout << "Exiting Negative_InputDoesNotStartWithPrefix test\n";
}
/**
 * @brief Test that player_StartsWith correctly handles the case where the prefix is an empty string
 *
 * This test verifies that when an empty string is provided as the prefix, the API player_StartsWith returns true.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 039@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**
 * | Variation / Step | Description                                                           | Test Data                                            | Expected Result                                                   | Notes      |
 * | :--------------: | --------------------------------------------------------------------- | ---------------------------------------------------- | ----------------------------------------------------------------- | ---------- |
 * | 01               | Initialize inputStr with "example" and prefix with an empty string, then call player_StartsWith API | inputStr = example, prefix = ""                      | Returns true; EXPECT_TRUE(result) assertion passes                | Should Pass |
 */
TEST(PlayerStartsWithTest, Edge_PrefixEmptyString) {
    std::cout << "Entering Edge_PrefixEmptyString test\n";

    char inputStr[50];
    char prefix[50];

    std::strncpy(inputStr, "example", sizeof(inputStr) - 1);
    inputStr[sizeof(inputStr) - 1] = '\0';
    std::strncpy(prefix, "", sizeof(prefix) - 1);
    prefix[sizeof(prefix) - 1] = '\0';

    std::cout << "Invoking player_StartsWith with inputStr: \"" << inputStr
              << "\" and prefix: \"" << prefix << "\" (empty string)\n";
    bool result = player_StartsWith(inputStr, prefix);
    std::cout << "Returned value: " << (result ? "true" : "false") << "\n";
    EXPECT_TRUE(result);
    
    std::cout << "Exiting Edge_PrefixEmptyString test\n";
}
/**
 * @brief Validate that player_StartsWith returns false when input string is NULL.
 *
 * This test verifies that the player_StartsWith function handles a NULL input string gracefully by returning false when provided with a valid non-empty prefix. The test ensures that even with a NULL input, the function does not crash and correctly indicates failure.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 040@n
 * **Priority:** High@n
 * 
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 * 
 * **Test Procedure:**@n
 * | Variation / Step | Description                                                                | Test Data                                  | Expected Result                                               | Notes       |
 * | :--------------: | -------------------------------------------------------------------------- | ------------------------------------------ | ------------------------------------------------------------- | ----------- |
 * | 01               | Invoke player_StartsWith with a NULL input string and a valid non-empty prefix | inputStr = NULL, prefix = nonempty         | Function should return false indicating the invalid input was handled | Should Fail |
 */
TEST(PlayerStartsWithTest, Negative_InputStringIsNull) {
    std::cout << "Entering Negative_InputStringIsNull test\n";

    // For inputStr as NULL, we don't need fixed size array; prefix will be assigned using fixed array.
    char prefix[50];
    std::strncpy(prefix, "nonempty", sizeof(prefix) - 1);
    prefix[sizeof(prefix) - 1] = '\0';

    std::cout << "Invoking player_StartsWith with inputStr: NULL and prefix: \"" << prefix << "\"\n";
    bool result = player_StartsWith(NULL, prefix);
    std::cout << "Returned value: " << (result ? "true" : "false") << "\n";
    EXPECT_FALSE(result);
    
    std::cout << "Exiting Negative_InputStringIsNull test\n";
}
/**
 * @brief Test the trim() function to remove leading and trailing whitespaces from a string
 *
 * This test verifies that the trim() function correctly removes spaces from both the beginning and end of a string. The test ensures that the function does not throw exceptions when invoked and that it produces the expected output (i.e., "Hello World" from the input "   Hello World   ").@n
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 041@n
 * **Priority:** High@n
 * 
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 * 
 * **Test Procedure:**@n
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Initialize the test input by copying a string with leading and trailing whitespaces into a fixed size character array. | input = "   Hello World   " | Character array initialized with the input string successfully. | Should be successful |
 * | 02 | Convert the fixed size character array to a std::string. | input from buffer = "   Hello World   ", output1 = str | std::string 'str' contains "   Hello World   ". | Should be successful |
 * | 03 | Call the trim() function to remove leading and trailing whitespaces from the std::string. | input = str ("   Hello World   "), output is modified str | trim() does not throw an exception and processes the string. | Should Pass |
 * | 04 | Verify that the trimmed string equals "Hello World". | output1 = str, expected = "Hello World" | EXPECT_EQ confirms that str equals "Hello World". | Should Pass |
 */
TEST(TrimTest, TrimStringWithLeadingAndTrailingWhitespaces) {
    std::cout << "Entering TrimStringWithLeadingAndTrailingWhitespaces test" << std::endl;
    
    char buffer[100];
    const char* input = "   Hello World   ";
    strncpy(buffer, input, sizeof(buffer) - 1);
    buffer[sizeof(buffer) - 1] = '\0';
    std::string str(buffer);
    
    std::cout << "Initial input string (from fixed size array): '" << str << "'" << std::endl;
    std::cout << "Invoking trim method with parameter: '" << str << "'" << std::endl;
    EXPECT_NO_THROW(trim(str));
    std::cout << "String after trim: '" << str << "'" << std::endl;
    
    EXPECT_EQ(str, "Hello World");
    std::cout << "Exiting TrimStringWithLeadingAndTrailingWhitespaces test" << std::endl;
}
/**
 * @brief Verify that the trim function handles a string with no whitespace correctly
 *
 * This test initializes a fixed-size character array with the string "NoWhiteSpace", converts it
 * to an std::string, and then passes it to the trim function. The test ensures that trim does not 
 * throw any exceptions and that the string remains unchanged after trimming.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 042@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**@n
 * | Variation / Step | Description                                                                             | Test Data                                         | Expected Result                                                    | Notes          |
 * | :--------------: | --------------------------------------------------------------------------------------- | ------------------------------------------------- | ------------------------------------------------------------------ | -------------- |
 * | 01               | Initialize a fixed-size character array with "NoWhiteSpace" and convert to std::string    | input = "NoWhiteSpace"                           | string is initialized as "NoWhiteSpace" without causing errors      | Should be successful |
 * | 02               | Invoke the trim function with the initialized string and verify no exceptions are thrown    | input1 = "NoWhiteSpace"                            | trim function does not throw any exception                          | Should Pass    |
 * | 03               | Assert that the string remains unchanged after trim                                       | input1 = "NoWhiteSpace", output1 = "NoWhiteSpace"   | The resulting string is equal to "NoWhiteSpace"                    | Should Pass    |
 */
TEST(TrimTest, TrimStringWithNoWhitespaces) {
    std::cout << "Entering TrimStringWithNoWhitespaces test" << std::endl;
    
    char buffer[100];
    const char* input = "NoWhiteSpace";
    strncpy(buffer, input, sizeof(buffer) - 1);
    buffer[sizeof(buffer) - 1] = '\0';
    std::string str(buffer);
    
    std::cout << "Initial input string (from fixed size array): '" << str << "'" << std::endl;
    std::cout << "Invoking trim method with parameter: '" << str << "'" << std::endl;
    EXPECT_NO_THROW(trim(str));
    std::cout << "String after trim: '" << str << "'" << std::endl;
    
    EXPECT_EQ(str, "NoWhiteSpace");
    std::cout << "Exiting TrimStringWithNoWhitespaces test" << std::endl;
}
/**
 * @brief Verify that the trim function correctly processes a string containing only whitespace characters.
 *
 * This test verifies that the trim function removes all whitespace from a string that initially consists solely of whitespace characters. The test creates a fixed size character buffer, copies a whitespace string into it, converts the buffer to a std::string, and then invokes the trim function. Finally, it verifies that the trimmed string is equal to an empty string.
 *
 * **Test Group ID:** Basic: 01
 * **Test Case ID:** 043
 * **Priority:** High
 *
 * **Pre-Conditions:** None
 * **Dependencies:** None
 * **User Interaction:** None
 *
 * **Test Procedure:**
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :----: | --------- | ---------- |-------------- | ----- |
 * | 01 | Create a fixed size character buffer and initialize it with a whitespace only string. | input = "    " | Buffer contains only whitespace string | Should be successful |
 * | 02 | Convert the buffer to std::string and log the initial value. | buffer = "    ", str = "    " | Initial string logs display whitespace string | Should be successful |
 * | 03 | Invoke the trim function on the std::string and log the operation. | str = "    " | Function executes without exception and removes whitespace | Should Pass |
 * | 04 | Validate that the trimmed string is an empty string. | str (after trim) = "" | EXPECT_EQ confirms trimmed string equals empty string | Should Pass |
 */
TEST(TrimTest, TrimStringContainingOnlyWhitespaceCharacters) {
    std::cout << "Entering TrimStringContainingOnlyWhitespaceCharacters test" << std::endl;
    
    char buffer[100];
    const char* input = "    ";
    strncpy(buffer, input, sizeof(buffer) - 1);
    buffer[sizeof(buffer) - 1] = '\0';
    std::string str(buffer);
    
    std::cout << "Initial input string (from fixed size array): '" << str << "'" << std::endl;
    std::cout << "Invoking trim method with parameter: '" << str << "'" << std::endl;
    EXPECT_NO_THROW(trim(str));
    std::cout << "String after trim: '" << str << "'" << std::endl;
    
    EXPECT_EQ(str, "");
    std::cout << "Exiting TrimStringContainingOnlyWhitespaceCharacters test" << std::endl;
}
/**
 * @brief Test to verify that the trim API correctly removes only leading whitespaces from a string
 *
 * This test verifies that the trim API removes leading whitespaces from an input string that originates from a fixed-size character buffer. The test creates a buffer, copies a string containing only leading whitespaces into it, converts it to a std::string object, and then invokes the trim function. It validates that the returned string is correctly trimmed to remove the unwanted leading spaces.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 044@n
 * **Priority:** High@n
 *
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 *
 * **Test Procedure:**@n
 * | Variation / Step | Description | Test Data | Expected Result | Notes |
 * | :--------------: | ----------- | --------- | --------------- | ----- |
 * | 01 | Initialize a fixed-size char buffer with a string containing only leading whitespaces, convert it to std::string, call trim API, and verify that the resulting string has no leading whitespaces | input = "   Leading", buffer size = 100, initial string = "   Leading", expected trimmed string = "Leading" | API should not throw and EXPECT_EQ should confirm the string equals "Leading" | Should Pass |
 */
TEST(TrimTest, TrimStringWithOnlyLeadingWhitespaces) {
    std::cout << "Entering TrimStringWithOnlyLeadingWhitespaces test" << std::endl;
    
    char buffer[100];
    const char* input = "   Leading";
    strncpy(buffer, input, sizeof(buffer) - 1);
    buffer[sizeof(buffer) - 1] = '\0';
    std::string str(buffer);
    
    std::cout << "Initial input string (from fixed size array): '" << str << "'" << std::endl;
    std::cout << "Invoking trim method with parameter: '" << str << "'" << std::endl;
    EXPECT_NO_THROW(trim(str));
    std::cout << "String after trim: '" << str << "'" << std::endl;
    
    EXPECT_EQ(str, "Leading");
    std::cout << "Exiting TrimStringWithOnlyLeadingWhitespaces test" << std::endl;
}
/**
 * @brief Verifies that the trim function correctly removes only trailing white spaces from a string
 *
 * This test case checks whether the trim() function properly removes trailing spaces from an input string that is read from a fixed-size array. It verifies that no exceptions are thrown during the operation and that the resulting string matches the expected output.
 *
 * **Test Group ID:** Basic: 01@n
 * **Test Case ID:** 045@n
 * **Priority:** High@n
 * 
 * **Pre-Conditions:** None@n
 * **Dependencies:** None@n
 * **User Interaction:** None@n
 * 
 * **Test Procedure:**
 * | Variation / Step | Description                                                                                   | Test Data                                                       | Expected Result                                                  | Notes         |
 * | :--------------: | --------------------------------------------------------------------------------------------- | --------------------------------------------------------------- | ---------------------------------------------------------------- | ------------- |
 * | 01               | Initialize a fixed-size buffer with an input string containing trailing white spaces            | input = "Trailing   "                                             | Buffer contains the string "Trailing   "                          | Should be successful |
 * | 02               | Invoke the trim() function to remove trailing white spaces in the string                        | string (from buffer) = "Trailing   "                               | No exception is thrown during the trim operation                   | Should Pass   |
 * | 03               | Verify that the trimmed string matches the expected result ("Trailing") using an assertion check | output after trim = "Trailing", expected output = "Trailing"         | The string after trim equals "Trailing" and test assertion passes    | Should Pass   |
 */
TEST(TrimTest, TrimStringWithOnlyTrailingWhitespaces) {
    std::cout << "Entering TrimStringWithOnlyTrailingWhitespaces test" << std::endl;
    
    char buffer[100];
    const char* input = "Trailing   ";
    strncpy(buffer, input, sizeof(buffer) - 1);
    buffer[sizeof(buffer) - 1] = '\0';
    std::string str(buffer);
    
    std::cout << "Initial input string (from fixed size array): '" << str << "'" << std::endl;
    std::cout << "Invoking trim method with parameter: '" << str << "'" << std::endl;
    EXPECT_NO_THROW(trim(str));
    std::cout << "String after trim: '" << str << "'" << std::endl;
    
    EXPECT_EQ(str, "Trailing");
    std::cout << "Exiting TrimStringWithOnlyTrailingWhitespaces test" << std::endl;
}