name: Build Component in Native Environment

on:
  pull_request:
    branches: [ develop , main ]
    paths: ['**/*.c', '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.h', '**/*.hpp', '**/*.sh']

jobs:
  build-player-interface-on-pr:
    name: Build player-interface component in github rdkcentral
    runs-on: ubuntu-latest
    container:
     image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Run unit tests
        run:  tail -f /dev/null

      - name: native build
        run: |
         apt-get update
         apt-get install -y sudo
         sudo apt-get install -y python3-pip
         sudo apt remove -y meson || true
         sudo pip3 install --upgrade meson
         hash -r
         yes | ./install-middleware.sh -s subtec
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}

                # Run L1 tests
      - name: Run unit tests
        working-directory: ./test/utests
        run: ./run.sh

        # Publish test results
      - name: Publish L1 test results
        if: ${{ !env.ACT }}
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Results
          path: test/utests/build/ctest-results.xml
          reporter: java-junit
            
        # Upload artifact (test/utests/build/ctest-results.xml)
      - name: Upload test result file (test/utests)
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: ctest-results-middleware-utests-${{ github.run_id }}
          path: test/utests/build/ctest-results.xml

        # Show failure
      - name: Show failure details (if any)
        # if: failure()
        run: tail -n 50 test/utests/build/ctest-results.xml || true
