name: Build Component in Native Environment

on:
  pull_request:
    branches: [ develop , main , feature/dev_sprint_pli ]
    paths: ['**/*.c', '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.h', '**/*.hpp', '**/*.sh']
  workflow_dispatch:

jobs:
  build-player-interface-on-pr:
    name: Build player-interface component in github rdkcentral
    runs-on: ubuntu-latest
    container:
     image: ubuntu:22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: native build
        run: |
         apt-get update
         apt-get install -y sudo
         sudo apt-get install -y python3-pip
         sudo apt remove -y meson || true
         sudo pip3 install --upgrade meson
         hash -r
         yes | ./install-middleware.sh -s subtec
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}
